### PR TITLE
update dependencies (npm-check-updates -a)

### PR DESCRIPTION
**Pull request by phueper**
Signed-off-by: Pattrick Hueper <phueper@hueper.net>

### CODE REVIEW

**Comment by hpurmann** [comment]
Did you try [greenkeeper.io](http://greenkeeper.io)? It's free for open source projects :)

**Comment by phueper** [comment]
Hmm... Looks interesting... Will try...
Though we don't have (and don't want to have) runtime dependencies but
"only" build /test time dependencies, so being always up-to-date is maybe
not that important...  But still sounds nice not having to look after the
devDependencies from time to time

--*sent from mobile device, please excuse spellinv mistakws*
Am 29.02.2016 10:05 nachm. schrieb "Hendrik Purmann" <
notifications@github.com>:

**Comment by pithu** [comment]
@hpurmann great idea, go for it ;)

**Comment by phueper** [comment]
If i understood the greenkeeper instructions right,  you as repo owner need
to enable it,  @pithu,  otherwise the PRs would go to my or @hpurmann s
repo... That would mean we'd still have to PR to the main repo again...
On the other hand... I haven't tried yet

--*sent from mobile device, please excuse spellinv mistakws*
Am 01.03.2016 7:46 vorm. schrieb "Philipp Thuerwaechter" <
notifications@github.com>:

**Comment by pithu** [comment]
Ok, i just read the greenkeeper docu, that sounds really easy ...

**Comment by phueper** [comment]
:+1:

**Comment by pithu** [comment]
greenkeeper is enabled for our repo. lets see how it worx

**Comment by phueper** [comment]
:ok:

**Pull request merged**
